/**
 * Embed Butterbase credentials for Edge SSR where platform-reserved
 * BUTTERBASE_* keys cannot be set, and app env may not bind to the worker.
 * Output is gitignored; generated at build from .env.local.
 */
import { readFileSync, writeFileSync, existsSync } from "fs";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = resolve(root, ".env.local");
const outPath = resolve(root, "src/lib/bb-embedded.ts");

const env = { ...process.env };
if (existsSync(envPath)) {
  for (const line of readFileSync(envPath, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const i = trimmed.indexOf("=");
    if (i < 0) continue;
    const key = trimmed.slice(0, i).trim();
    const val = trimmed.slice(i + 1).trim();
    if (!(key in env) || !env[key]) env[key] = val;
  }
}

const apiKey =
  env.SYNAPSE_BB_KEY || env.BUTTERBASE_API_KEY || env.SYNAPSE_DATA_API_KEY || "";
const appId =
  env.SYNAPSE_BB_APP_ID || env.BUTTERBASE_APP_ID || env.SYNAPSE_APP_ID || "";
const apiUrl =
  env.SYNAPSE_BB_URL ||
  env.BUTTERBASE_API_URL ||
  "https://api.butterbase.ai/v1";

writeFileSync(
  outPath,
  `/** Auto-generated by scripts/embed-bb-env.mjs — do not commit. */
export const BB_EMBEDDED = {
  apiKey: ${JSON.stringify(apiKey)},
  appId: ${JSON.stringify(appId)},
  apiUrl: ${JSON.stringify(apiUrl)},
} as const;
`
);

console.log(
  `embed-bb-env: wrote ${outPath} (key=${apiKey ? "set" : "missing"}, app=${appId || "missing"})`
);
